name: 'Tests: node.js >= 22.21'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^22.21 || ^24.11 || >= 25.2'
      type: minors
      command: npm run tests-only
